"""
AI Service - Gemini text and image generation.
"""
import json
import io
from PIL import Image
from google import genai
from google.genai import types
from fastapi import HTTPException
from config import GEMINI_API_KEY, GEMINI_TEXT_MODEL, GEMINI_IMAGE_MODEL, STRUCTURED_OUTPUT_PROMPT

# Initialize Gemini client
client = genai.Client(api_key=GEMINI_API_KEY)


def generate_structured_output(holiday: str, description: str = None) -> dict:
    """Generate structured output with prompt and caption using Gemini Flash.

    Args:
        holiday: The holiday name/prompt
        description: Optional detailed description of the holiday for better context
    """
    # Build the prompt with description if available
    if description:
        holiday_context = f"{holiday}. Context: {description}"
    else:
        holiday_context = holiday

    prompt = STRUCTURED_OUTPUT_PROMPT.format(holiday=holiday_context)

    response = client.models.generate_content(
        model=GEMINI_TEXT_MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(response_mime_type="application/json"),
    )

    try:
        result = json.loads(response.text)
        return result
    except json.JSONDecodeError:
        raise HTTPException(
            status_code=500, detail="Failed to parse Gemini response as JSON"
        )


def generate_image(prompt: str) -> Image.Image:
    """Generate an image using Gemini image model."""
    response = client.models.generate_content(
        model=GEMINI_IMAGE_MODEL,
        contents=[prompt],
        config=types.GenerateContentConfig(
            response_modalities=["IMAGE", "TEXT"],
            image_config=types.ImageConfig(
                aspect_ratio="1:1",
                image_size="1K",
            )
        )
    )

    # Extract the generated image from response
    for part in response.candidates[0].content.parts:
        if part.inline_data is not None:
            image_data = part.inline_data.data
            return Image.open(io.BytesIO(image_data))

    raise HTTPException(status_code=500, detail="No image generated by Gemini")
